[project]
name = "subnet-uid-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "async-substrate-interface==1.0.0",
    "bt-decode==0.5.0a2",
    "bittensor==9.0.0",
    "bittensor-cli==9.0.0",
]
